title: <p align="center"> Priyadharshini Vijayan </p>
logo: /assets/img/MyPic.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/priyadharshini-vijayan-6bb526a5/">LinkedIn</a> |
  <a href="https://github.com/PriyadharshiniVijayan">GitHub</a>
  
  <br>   
  I'm a Java backend developer transitioning into ML and AI Engineer.
  <br>
  </p>



theme: jekyll-theme-minimal
